### PR TITLE
Usability

### PR DESCRIPTION
**Pull request by rusq**
* Make a temporary copy instead and operate on it
* Describe the -time-format parameter and the time format in the README file
* remove the -f command line flag and use the [optional] first positional argument as the filename.
* If the filename is not specified, try locate and make a temporary copy of the default callhistory file.

### CODE REVIEW

**Comment by wot4me** [comment]
pls make a build/packege for macos and win, thx

**Comment by rusq** [comment]
@wot4me hey, thanks for your interest.

Binaries uploaded to [Release v1.1.2](https://github.com/rusq/osx-callhistory-decryptor/releases/tag/v1.1.2)

**Comment by wot4me** [comment]
win build error msg
 "Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"

thx a lot for your work

**Comment by rusq** [comment]
@wot4me had to find the windows machine for that to work - updated the archive, [should work now](https://github.com/rusq/osx-callhistory-decryptor/releases/download/v1.1.2/osx-callhistory-decryptor-1.1.2-win64.zip).

**Comment by wot4me** [comment]
nice work m8! thx and best wish from Prague.

**Pull request merged**
